### PR TITLE
Fixed a crash that happens from edges having no IDs

### LINKED ISSUE #84: The webapp crashes following a certain path
**Describe the bug**
If you follow the steps below, the webapp will crash.

**To Reproduce**
1. Search for  "scan"
2. Go to home
3. Type a new search term "can"
4. The webapp crashes

**Expected behavior**
This shouldn't happen

**Screenshots**
Screen Shot 2022-10-02 at 1 09 25 PM

### PR DESCRIPTION
**Pull request by thedarkspy**
Fixes #84

### CODE REVIEW

File: api/controllers/contracts.js [hunk 1]
```diff
@@ -341,6 +341,7 @@ const getContractTopLinks = asyncHandler(async (request, response, next) => {
     },
   ];
   let edges = [];
+  let edgeIndex = 0;
   contractTopLinksResult.map((row) => {
```
Comment (boshmaf) [inline api/controllers/contracts.js]: You can use the map's index here to assign unique ids to in and out edges via `in-${index}` and `out-${index}`
