### PR TITLE
Handle N/A dates when showing in the table views

### LINKED ISSUE #160: Security audit initial Completed At value sets as Invalid Date
**Describe the bug**
$subject

Screenshot 2022-11-26 at 10 23 52 AM

**To Reproduce**
1. Go to 'https://kansa.cibr.qcri.org/audits'
2. Click on 'Request an audit.'
3. Submit

**Expected behavior**

**Screenshots**

### PR DESCRIPTION
**Pull request by sajithaliyanage**
- Closes #160

### CODE REVIEW

File: web/src/utils/common.js [hunk 1]
```diff
@@ -33,5 +33,7 @@ export const titleShortener = (type, value) => {
 };
 
 export const formatDateString = (dateString, dateOptions = {}) => {
-  return new Date(dateString).toLocaleDateString('en-CA', dateOptions).replace(',', '');
+  return dateString != 'N/A'
+    ? new Date(dateString).toLocaleDateString('en-CA', dateOptions).replace(',', '')
+    : dateString;
```
Comment (thedarkspy) [inline web/src/utils/common.js:38]: Better check if it is a valid date otherwise return whatever was given (or N/A)

**Review by thedarkspy — CHANGES_REQUESTED** [review]

**Review by thedarkspy — APPROVED** [review]
