### PR TITLE
Issue #133: report dates on the webapp in local system time not server

### LINKED ISSUE #133: Non-blockchain dates are reported in server time
**Describe the bug**
The scanned on field in vulnerabilities view and createdAt and completedAt in the audits view show dates in server time (UTC), but to the user it makes more sense to show in local time.

**To Reproduce**
1. Go to any contract view
2. 4. See error in the vulnerabilities table (scanned on column).

**Expected behavior**
Date and time should reflect your's local time, not the server's,=.

### PR DESCRIPTION
**Pull request by thedarkspy**
Fixes #133

### CODE REVIEW

File: web/src/components/Contract/Summary/Summary.js [hunk 1]
```diff
@@ -79,6 +76,13 @@ const Summary = () => {
           let value = contract[key];
           value = !value || value === -1 ? 'N/A' : value;
 
+          if (key === 'auditedAt')
```
Comment (boshmaf) [inline web/src/components/Contract/Summary/Summary.js:79]: Need to remove the comma between date and time.

File: web/src/components/DataTableRaw/DataTableRaw.js [hunk 2]
```diff
@@ -98,22 +98,37 @@ export const DataTableRaw = (props) => {
...
+      column.id === 'swc'
+        ? 'https://swcregistry.io/docs/SWC-' + row[column.id]
+        : basePath + row[column.id];
+
+    const dateCells = [
+      'createdAt',
+      'scannedOn',
+      'auditedAt',
+      'timestamp',
+      'scannedOn',
```
Comment (boshmaf) [inline web/src/components/DataTableRaw/DataTableRaw.js:113]: Duplicate. Also, scannedOn is date only, no time.

**Review by boshmaf — CHANGES_REQUESTED** [review]

**Comment by thedarkspy** [comment]
Review comments addressed. Final view is below:

**Review by boshmaf — APPROVED** [review]
